# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-15 02:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_reviews'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='books',
        ),
        migrations.RemoveField(
            model_name='user',
            name='reviews',
        ),
    ]
