# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-12 19:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo_ninjas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dojo',
            name='desc',
            field=models.CharField(default='default desc', max_length=255),
            preserve_default=False,
        ),
    ]
