# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-12 20:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_authors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='authors',
            name='notes',
            field=models.TextField(default='This is an author', verbose_name=500),
            preserve_default=False,
        ),
    ]
