# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-30 20:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_login',
            name='age',
            field=models.IntegerField(default=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user_login',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='user_login',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
